"""The worker protocol: daemon ↔ worker messages (design Appendix A; plan.md P1).

The definitions live in ``narration_worker.protocol`` (``workers/common``, standard library only), because
the worker venvs carry that package and never this one. This module re-exports them, so server code and
the workers type-check against one definition. See that module for the framing and the rules.
"""

from __future__ import annotations

from narration_worker.protocol import (
    COMMON_OPS,
    FAKE_OPS,
    MAX_LINE_BYTES,
    OPS_BY_ROLE,
    PROTOCOL_VERSION,
    QA_OPS,
    QWEN3_OPS,
    WORKER_ERROR_CODES,
    AlignReply,
    AlignRequest,
    AsrWord,
    AudioReply,
    Capabilities,
    Controls,
    DesignRequest,
    DeterminismSettings,
    EmbedReply,
    EmbedRequest,
    F0Reply,
    F0Request,
    Fingerprint,
    Generation,
    HelloReply,
    LoadReply,
    LoadRequest,
    ModelRef,
    Op,
    PrepareVoiceRequest,
    ProfileReply,
    ProfileRequest,
    QwenSettings,
    Reply,
    Request,
    SynthesizeRequest,
    TokenSpan,
    TranscribeReply,
    TranscribeRequest,
    WorkerError,
    WorkerErrorCode,
    WorkerRole,
)

__all__ = [
    "COMMON_OPS",
    "FAKE_OPS",
    "MAX_LINE_BYTES",
    "OPS_BY_ROLE",
    "PROTOCOL_VERSION",
    "QA_OPS",
    "QWEN3_OPS",
    "WORKER_ERROR_CODES",
    "AlignReply",
    "AlignRequest",
    "AsrWord",
    "AudioReply",
    "Capabilities",
    "Controls",
    "DesignRequest",
    "DeterminismSettings",
    "EmbedReply",
    "EmbedRequest",
    "F0Reply",
    "F0Request",
    "Fingerprint",
    "Generation",
    "HelloReply",
    "LoadReply",
    "LoadRequest",
    "ModelRef",
    "Op",
    "PrepareVoiceRequest",
    "ProfileReply",
    "ProfileRequest",
    "QwenSettings",
    "Reply",
    "Request",
    "SynthesizeRequest",
    "TokenSpan",
    "TranscribeReply",
    "TranscribeRequest",
    "WorkerError",
    "WorkerErrorCode",
    "WorkerRole",
]
